import {
  Target,
  Zap,
  Dumbbell,
  RotateCcw,
  ArrowUp,
  ArrowDown,
  Move,
  Gauge,
  HeartPulse,
  Grid,
  CheckCircle,
} from 'lucide-react';

export const categories = [
  {
    id: 'mohamed',
    name: 'تمارين برنامج محمد',
    icon: <Dumbbell className="w-4 h-4 text-blue-500" />,
  },
  {
    id: 'isometrics',
    name: 'ثباتات (Isometrics)',
    icon: <CheckCircle className="w-4 h-4" />,
  },
  {
    id: 'upper',
    name: 'أبر (Upper Body)',
    icon: <ArrowUp className="w-4 h-4" />,
  },
  {
    id: 'lower',
    name: 'لووار (Lower Body)',
    icon: <ArrowDown className="w-4 h-4" />,
  },
  { id: 'core', name: 'كور (Core)', icon: <Grid className="w-4 h-4" /> },
  { id: 'power', name: 'باور (Power)', icon: <Zap className="w-4 h-4" /> },
  {
    id: 'mobility',
    name: 'موبيلتي واسترتشات',
    icon: <RotateCcw className="w-4 h-4" />,
  },
  {
    id: 'cod',
    name: 'تغيير الاتجاه (Agility)',
    icon: <Move className="w-4 h-4" />,
  },
  {
    id: 'acceleration',
    name: 'تسارع (Acceleration)',
    icon: <Gauge className="w-4 h-4" />,
  },
  { id: 'max_speed', name: 'سرعة قصوى', icon: <Target className="w-4 h-4" /> },
  {
    id: 'endurance',
    name: 'تحمل (Zones 1-5)',
    icon: <HeartPulse className="w-4 h-4" />,
  },
];

export const exerciseLibrary = {
  mohamed: [
    {
      name: 'موبيليتي سفلي (Lower Mobility)',
      target: 'كاحل وحوض',
      sets: '1',
      reps: '10',
      rest: '-',
      notes: 'Ankle Dorsiflexion + 90/90 + Side Lunges',
    },
    {
      name: 'الثباتات الـ 6 (6 Isometrics)',
      target: 'أوتار وأربطة',
      sets: '1',
      reps: '60 ثانية',
      rest: '30ث',
      notes: 'Wall Sit | Bridge | Calf | Superman | Split Sq | Spike Press',
    },
    {
      name: 'قفز كاحل + قفز صندوق (Pogo + Box Jumps)',
      target: 'تفاعل و ارتقاء',
      sets: '4',
      reps: '10 + 5',
      rest: '90ث',
      notes: 'Pogo Jumps 10x ➔ Box Jumps 5x',
    },
    {
      name: 'ميكانيكا الهبوط (Landing Mechanics)',
      target: 'وقاية ركبة',
      sets: '4',
      reps: '8',
      rest: '90ث',
      notes: 'سقوط من صندوق لثبات سكوات ولثبات طعن',
    },
    {
      name: 'إسكوات أمامي/خلفي (Front/Back Squat)',
      target: 'قوة أرجل',
      sets: '4',
      reps: '8',
      rest: '120ث',
      notes: 'النزول البطيء لحماية الركبة',
    },
    {
      name: 'عجلة البطن (Ab Wheel Rollout)',
      target: 'مقاومة تمدد',
      sets: '4',
      reps: '8',
      rest: '-',
      notes: 'لمنع تقوس الظهر أثناء القفز',
    },
    {
      name: 'ديدليفت رجل مفرودة (Stiff-Leg Deadlift)',
      target: 'خلفيات أرجل',
      sets: '4',
      reps: '8',
      rest: '120ث',
      notes: 'أقصى إطالة للخلفيات',
    },
    {
      name: 'بالوف برس (Pallof Press)',
      target: 'كور/منع دوران',
      sets: '4',
      reps: '10 / جنب',
      rest: '-',
      notes: 'منع الدوران للحوض',
    },
    {
      name: 'طعن بالدمبلز (Dumbbell Lunges)',
      target: 'توازن أحادي',
      sets: '4',
      reps: '8',
      rest: '90ث',
      notes: 'توازن الرجلين الأحادي',
    },
    {
      name: 'بلانك جانبي ستار (Side Plank Star)',
      target: 'خواصر',
      sets: '4',
      reps: '30ث',
      rest: '-',
      notes: 'رفع الرجل وثبات',
    },
    {
      name: 'طلوع الصندوق بوزن (Weighted Step-Ups)',
      target: 'جلوتس',
      sets: '4',
      reps: '8',
      rest: '90ث',
      notes: 'دفع الجلوتس',
    },
    {
      name: 'عتلة بطن (Deadbug)',
      target: 'توازن كور',
      sets: '4',
      reps: '12',
      rest: '-',
      notes: 'بطيء جداً للحماية',
    },
    {
      name: 'دفع حوض بالبار (Barbell Hip Thrust)',
      target: 'جلوتس/باور',
      sets: '4',
      reps: '10',
      rest: '90ث',
      notes: 'ثبات ثانيتين في الأعلى',
    },
    {
      name: 'بلانك مشدود (RKC Plank)',
      target: 'تفعيل كامل',
      sets: '4',
      reps: '20ث',
      rest: '-',
      notes: 'أقصى شد للكور',
    },
    {
      name: 'سمانة واقف (Standing Calf Raises)',
      target: 'امتصاص',
      sets: '4',
      reps: '15',
      rest: '60ث',
      notes: 'لامتصاص صدمات الهبوط',
    },
    {
      name: 'مكوك الطائرة + كارديو (Shuttle Run + Cardio)',
      target: 'تحمل',
      sets: '4',
      reps: '10دق',
      rest: '1:3',
      notes: 'مكوك 3-6-9 متر يليه عجلة/جري',
    },
    {
      name: 'موبيليتي علوي + تحركات (Upper Mobility + Shuffles)',
      target: 'كتف',
      sets: '1',
      reps: 'إحماء',
      rest: '90ث',
      notes: 'Shoulder Dislocates + Lateral Shuffles',
    },
    {
      name: 'بنش برس بالبار (Barbell Bench Press)',
      target: 'صدر',
      sets: '4',
      reps: '8',
      rest: '120ث',
      notes: 'قوة دفع',
    },
    {
      name: 'عقلة نيجاتيف (Negative Pull-ups)',
      target: 'ظهر',
      sets: '4',
      reps: '8',
      rest: '120ث',
      notes: 'نزول ببطء شديد في 5 ثواني',
    },
    {
      name: 'ضغط كتف (Overhead Press)',
      target: 'كتف علوي',
      sets: '4',
      reps: '8',
      rest: '120ث',
      notes: 'بار يوم 2 / دمبل يوم 4 لقوة دفع الكرة',
    },
    {
      name: 'بنش دمبلز (DB Bench Press)',
      target: 'صدر/توازن',
      sets: '4',
      reps: '8',
      rest: '90ث',
      notes: 'فلات / مائل',
    },
    {
      name: 'سحب جالس بالكابل (Seated Cable Row)',
      target: 'سمك ظهر',
      sets: '4',
      reps: '8',
      rest: '90ث',
      notes: 'تحكم في المدى الحركي',
    },
    {
      name: 'باي وتراي وضغط (Arm Complex)',
      target: 'ذراعين',
      sets: '4',
      reps: '10',
      rest: '60ث',
      notes: 'تمرين مجمع لنهاية الحصة',
    },
    {
      name: 'فرامل الكتف (Shoulder Deceleration)',
      target: 'كتف خلفي',
      sets: '4',
      reps: '15',
      rest: '45ث',
      notes: 'Face Pulls + Band Ext. Rotations',
    },
    {
      name: 'موبيليتي وثباتات بوزن (Weighted ISOs & Mobility)',
      target: 'أربطة',
      sets: '1',
      reps: '45s',
      rest: '30ث',
      notes: 'سكوات حائط دمبل | بريدج | سمانة | طعن بوزن',
    },
    {
      name: 'تحركات في الملعب (Court Footwork)',
      target: 'خفة قدم',
      sets: '1',
      reps: 'متغير',
      rest: '60ث',
      notes: 'متدرجة الصعوبة كل أسبوع حسب المركز',
    },
    {
      name: 'تفعيل العصب (Overcoming Isometrics)',
      target: 'جهاز عصبي',
      sets: '3',
      reps: '6ث',
      rest: '120ث',
      notes: 'اضغط البار بأقصى قوة لتنبيه العصب',
    },
    {
      name: 'قفزة الهجوم (Approach Jump)',
      target: 'ارتقاء',
      sets: '4',
      reps: '4',
      rest: '90ث',
      notes: 'محاكاة خطوة القفز للمعد/الضارب',
    },
    {
      name: 'قفز عميق للهدف (Depth Jump to Target)',
      target: 'تفاعل سريع',
      sets: '4',
      reps: '4',
      rest: '120ث',
      notes: 'سقوط ➔ ارتداد ➔ حركة فنية في الهواء',
    },
    {
      name: 'باور كلين من الفخذ (Hang Power Clean)',
      target: 'انفجار',
      sets: '5',
      reps: '5',
      rest: '120ث',
      notes: 'سحب انفجاري',
    },
    {
      name: 'بوش جيرك (Push Jerk)',
      target: 'باور علوي',
      sets: '4',
      reps: '5',
      rest: '180ث',
      notes: 'دفع بالقدمين',
    },
    {
      name: 'إسكوات من الثبات (Pin Squats)',
      target: 'قوة مطلقة',
      sets: '5',
      reps: '5',
      rest: '15ث',
      notes: 'زاوية أعلى من 90. البداية من الثبات.',
    },
    {
      name: 'قفز من الجلوس (Seated Box Jumps)',
      target: 'قوة من الثبات',
      sets: '4',
      reps: '5',
      rest: '15ث',
      notes: 'انفجار بدون مرجحة',
    },
    {
      name: 'ضغط دمبل على الكرة (Swiss Ball DB Press)',
      target: 'توازن متقاطع',
      sets: '4',
      reps: '8',
      rest: '180ث',
      notes: 'توازن متقاطع برجل مرفوعة',
    },
    {
      name: 'ديدليفت روماني ثقيل (Heavy RDL)',
      target: 'أوتار خلفية',
      sets: '4',
      reps: '6',
      rest: '15ث',
      notes: 'أوزان عالية لتحمل الأوتار',
    },
    {
      name: 'قفز عريض (Broad Jumps)',
      target: 'قوة أفقية',
      sets: '4',
      reps: '4',
      rest: '15ث',
      notes: 'مسافة أقصى قفز',
    },
    {
      name: 'سحب كيتل بوضع الدب (Bear Crawl KB Pull)',
      target: 'كور متقدم',
      sets: '4',
      reps: '10',
      rest: '150ث',
      notes: 'وضع الدب وسحب الكيتل',
    },
    {
      name: 'إسكوات بلغاري (Bulgarian Split Squats)',
      target: 'قوة أحادية',
      sets: '4',
      reps: '6',
      rest: '90ث',
      notes: 'بوزن إضافي',
    },
    {
      name: 'قطنية على الجهاز (Back Extensions)',
      target: 'قطنية',
      sets: '4',
      reps: '12',
      rest: '-',
      notes: 'تحكم تام',
    },
    {
      name: 'رفع الحوض (Glute Bridges)',
      target: 'تفعيل جلوتس',
      sets: '4',
      reps: '15',
      rest: '90ث',
      notes: 'W1-W2 زوجي، W3-W4 فردي',
    },
    {
      name: 'موبيليتي وثباتات علوية (Upper Mobility & ISOs)',
      target: 'مفاصل كتف',
      sets: '1',
      reps: '45s',
      rest: '30ث',
      notes: 'ضغط دمبل ثبات | عقلة ثبات',
    },
    {
      name: 'تفعيل العصب بنش (Overcoming Iso Bench)',
      target: 'عصب علوي',
      sets: '3',
      reps: '6ث',
      rest: '120ث',
      notes: 'ضغط البار للتهيئة',
    },
    {
      name: 'باور سناتش (Power Snatch)',
      target: 'انفجار علوي',
      sets: '4',
      reps: '4',
      rest: '180ث',
      notes: 'سحب البار فوق الرأس',
    },
    {
      name: 'رمي كرة للخلف (Backward MB Throws)',
      target: 'قوة دفع',
      sets: '4',
      reps: '5',
      rest: '120ث',
      notes: 'Overhead Backward Throws',
    },
    {
      name: 'بنش برس ثقيل (Heavy Bench Press)',
      target: 'قوة علوية',
      sets: '5',
      reps: '5',
      rest: '15ث',
      notes: 'بناء قوة أساسية',
    },
    {
      name: 'رمي كرة للصدر (MB Chest Pass)',
      target: 'انفجار الصدر',
      sets: '4',
      reps: '5',
      rest: '15ث',
      notes: 'دفع بأقصى سرعة',
    },
    {
      name: 'تجديف بلانك برجل مرفوعة (Bird-Dog Row)',
      target: 'كور وسحب',
      sets: '4',
      reps: '8',
      rest: '150ث',
      notes: 'توازن عالبنش',
    },
    {
      name: 'عقلة بوزن إضافي (Weighted Pull-ups)',
      target: 'قوة الظهر',
      sets: '4',
      reps: '5',
      rest: '-',
      notes: 'بأوزان إضافية',
    },
    {
      name: 'ستيب أب انفجاري (Explosive Step-Ups)',
      target: 'انفجار أحادي',
      sets: '4',
      reps: '6',
      rest: '15ث',
      notes: 'دفع قوي لفوق',
    },
    {
      name: 'وثب جانبي انفجاري (Lateral Bounds)',
      target: 'قوة جانبية',
      sets: '4',
      reps: '6',
      rest: '120ث',
      notes: 'تحكم وتوازن',
    },
    {
      name: 'إطالة سبايدر مان (Spiderman Lunge)',
      target: 'إطالة ديناميكية',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'منشار البطن المتقدم (Advanced Body Saw)',
      target: 'كور',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'قفز المتزلج الجانبي (Lateral Skater Jumps)',
      target: 'رشاقة',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'بلانك مع سحب وزن (Plank Sandbag Drag)',
      target: 'كور',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'بيربي مع قفز عريض (Burpee Broad Jumps)',
      target: 'باور',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'إطالة العقرب (Scorpion Stretch)',
      target: 'استشفاء',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'أرجحة جمباز مع ضمة (Hollow Rock to V-Up)',
      target: 'كور',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'قفز كاحل / ركبة عالية (Pogo / High Knees)',
      target: 'سرعة',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'إسكوات جانبي (Cossack Squats)',
      target: 'موبيلتي',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
    {
      name: 'دوران روسي سريع (Fast Russian Twist)',
      target: 'كور',
      sets: '4',
      reps: '45s',
      rest: '15s',
      notes: 'سيركيت',
    },
  ],
  isometrics: [
    {
      name: 'Wall Sit (جلوس الحائط)',
      target: 'الرجل الأمامية (Quads)',
      sets: '3',
      reps: '45-60 ثانية',
      rest: '60 ث',
      notes: 'ركبة بزاوية 90، ممتاز لوقاية الركبة',
    },
    {
      name: 'Isometric Split Squat Hold',
      target: 'استقرار الحوض والأرجل',
      sets: '3',
      reps: '30 ثانية/رجل',
      rest: '45 ث',
      notes: 'الركبة الخلفية لا تلامس الأرض بسنتيمتر واحد',
    },
    {
      name: 'Copenhagen Plank Hold',
      target: 'الضامة (Adductors)',
      sets: '3',
      reps: '20-30 ثانية/جهة',
      rest: '60 ث',
      notes: 'أساسي لمنع مزق الضامة',
    },
  ],
  upper: [
    {
      name: 'Bench Press (بنش برس مستوي)',
      target: 'الصدر والترايسبس',
      sets: '3-5',
      reps: '5-12',
      rest: '2-3 د',
      notes: 'تثبيت القدمين، قبض الكتفين للخلف للحماية',
    },
    {
      name: 'Incline DB Press (تجميع عالي)',
      target: 'أعلى الصدر',
      sets: '3-4',
      reps: '8-12',
      rest: '90 ث',
      notes: 'زاوية الدكة 30 درجة، تحكم كامل في النزول',
    },
    {
      name: 'Barbell Rows (تجديف بالبار)',
      target: 'الظهر العريض (Lats)',
      sets: '3-4',
      reps: '8-12',
      rest: '90 ث',
      notes: 'الظهر مستقيم، سحب البار نحو منطقة السرة',
    },
  ],
  lower: [
    {
      name: 'Back Squat (سكوات خلفي)',
      target: 'الأرجل والجلوتس',
      sets: '3-5',
      reps: '3-8',
      rest: '2-3 د',
      notes: 'النزول لزاوية 90 أو أعمق مع الحفاظ على استقامة الظهر',
    },
    {
      name: 'Romanian Deadlift - RDL',
      target: 'الرجل الخلفية، الجلوتس',
      sets: '3-4',
      reps: '8-10',
      rest: '2 د',
      notes: 'دفع الحوض للخلف، ثني الركبة قليلاً جداً',
    },
    {
      name: 'Bulgarian Split Squat',
      target: 'الأرجل (أحادي الجانب)',
      sets: '3',
      reps: '8-12 / رجل',
      rest: '90 ث',
      notes: 'القدم الخلفية على دكة، التركيز على التوازن',
    },
  ],
  core: [
    {
      name: 'Plank (بلانك)',
      target: 'مقاومة التمدد للكور',
      sets: '3',
      reps: '45-60 ثانية',
      rest: '60 ث',
      notes: 'شفط البطن للداخل، عصر الجلوتس',
    },
    {
      name: 'Dead Bug (الحشرة الميتة)',
      target: 'التحكم، البطن السفلية',
      sets: '3',
      reps: '12 / جهة',
      rest: '60 ث',
      notes: 'ضغط أسفل الظهر على الأرض بقوة طوال التمرين',
    },
    {
      name: 'Pallof Press',
      target: 'مقاومة دوران الجذع',
      sets: '3',
      reps: '10 لكل جهة',
      rest: '60 ث',
      notes: 'الثبات عند فرد الذراعين لثانيتين',
    },
  ],
  power: [
    {
      name: 'Box Jumps (قفز على الصندوق)',
      target: 'قوة الأرجل الانفجارية',
      sets: '4',
      reps: '3-5',
      rest: '2 د',
      notes: 'القفز بأقصى قوة، النزول بهدوء لتجنب صدمة الركبة',
    },
    {
      name: 'Medicine Ball Slams',
      target: 'قوة انفجارية علوية والكور',
      sets: '4',
      reps: '5-8',
      rest: '90 ث',
      notes: 'الرفع لأقصى نقطة، الضرب بالأرض بعنف',
    },
    {
      name: 'Power Clean (كلين)',
      target: 'انفجارية شاملة للجسم',
      sets: '3-5',
      reps: '2-5',
      rest: '3 د',
      notes: 'تمرين تقني، الحركة السريعة تبدأ من تمدد الحوض',
    },
  ],
  mobility: [
    {
      name: '90/90 Hip Stretch',
      target: 'دوران الحوض',
      sets: '2',
      reps: '45 ث / جهة',
      rest: 'بدون',
      notes: 'الزوايا 90 درجة، الصدر لأعلى',
    },
    {
      name: 'Cat-Cow (القط والبقرة)',
      target: 'مرونة العمود الفقري',
      sets: '2',
      reps: '10 حركات',
      rest: 'بدون',
      notes: 'تنفس متناسق مع الحركة لتليين الفقرات',
    },
    {
      name: "World's Greatest Stretch",
      target: 'موبيلتي شاملة',
      sets: '2',
      reps: '5 / جهة',
      rest: 'بدون',
      notes: 'النزول بوضعية الطعن العميق والدوران لأعلى',
    },
  ],
  cod: [
    {
      name: '5-10-5 Pro Agility Drill',
      target: 'تغيير الاتجاه الجانبي',
      sets: '4',
      reps: '1 يمين / 1 يسار',
      rest: '90 ث',
      notes: 'انخفاض مركز الثقل عند لمس الخط لتغيير أسرع',
    },
    {
      name: 'T-Drill',
      target: 'الأمام، الجانبي، والخلفي',
      sets: '4',
      reps: '1 كامل',
      rest: '90 ث',
      notes: 'التركيز على حركة القدمين الجانبية السريعة (Shuffle)',
    },
    {
      name: 'L-Drill (3 Cone Drill)',
      target: 'تغيير الاتجاه حول الزوايا',
      sets: '4',
      reps: '1 كامل',
      rest: '90 ث',
      notes: 'الجري في شكل حرف L حول الأقماع مع التفاف ضيق',
    },
  ],
  acceleration: [
    {
      name: 'Wall Drills (Piston Action)',
      target: 'وضع الجسم وحركة الأرجل',
      sets: '3',
      reps: '10 ثواني عمل',
      rest: '45 ث',
      notes: 'الميل على الحائط 45 درجة، ضرب الركبة كالمكبس',
    },
    {
      name: 'Falling Starts',
      target: 'زاوية التسارع الطبيعية',
      sets: '4',
      reps: '10 متر جري',
      rest: '60 ث',
      notes: 'السقوط للأمام حتى فقدان التوازن ثم الانطلاق',
    },
    {
      name: 'Push-up Starts',
      target: 'التسارع من السكون التام',
      sets: '4',
      reps: '10 متر جري',
      rest: '60 ث',
      notes: 'البدء من وضع الانبطاح، نهوض سريع جداً والانطلاق',
    },
  ],
  max_speed: [
    {
      name: 'Flying 10s',
      target: 'السرعة القصوى المطلقة',
      sets: '4',
      reps: '10 متر سريع جداً',
      rest: '3 د',
      notes: 'تسارع تدريجي 20 متر، ثم 10 متر بـ 100% من السرعة',
    },
    {
      name: 'Flying 20s',
      target: 'الحفاظ على السرعة القصوى',
      sets: '3-4',
      reps: '20 متر 100%',
      rest: '4 د',
      notes: 'مثل تمرين Flying 10s ولكن الحفاظ على السرعة لمسافة أطول',
    },
    {
      name: 'Wicket Drills (Mini Hurdles)',
      target: 'إيقاع وطول الخطوة',
      sets: '4',
      reps: 'مسار حواجز',
      rest: '2 د',
      notes: 'ضبط مسافات الحواجز لإجبار اللاعب على رفع الركبة',
    },
  ],
  endurance: [
    {
      name: '(ZONE 1) Active Recovery Walk',
      target: 'الاستشفاء وتنشيط الدورة الدموية',
      sets: '1',
      reps: '45-60 دقيقة',
      rest: 'مستمر',
      notes: 'مجهود خفيف جداً، يجب أن تكون قادراً على التنفس من الأنف',
    },
    {
      name: '(ZONE 1) Pool Swim / Walk',
      target: 'تفريغ اللاكتيك بضغط مائي',
      sets: '1',
      reps: '30 دقيقة',
      rest: 'مستمر',
      notes: 'سباحة خفيفة أو مشي داخل المسبح لتقليل الجاذبية',
    },
    {
      name: '(ZONE 2) Long Slow Distance',
      target: 'تطوير كفاءة الميتوكندريا',
      sets: '1',
      reps: '60-90 دقيقة',
      rest: 'مستمر',
      notes: 'أهم زون لبناء التحمل. جري بطيء، النبض 60-70%',
    },
  ],
};
